//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadsPakistan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int M_ID { get; set; }
        public string subject { get; set; }
        public Nullable<int> C_ID { get; set; }
        public Nullable<int> MT_ID { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual MessageType MessageType { get; set; }
    }
}
