//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadsPakistan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sadspakEntities : DbContext
    {
        public sadspakEntities()
            : base("name=sadspakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressLocation> AddressLocations { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contacttype> Contacttypes { get; set; }
        public virtual DbSet<Donatetype> Donatetypes { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<DonationScheme> DonationSchemes { get; set; }
        public virtual DbSet<img> imgs { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessageType> MessageTypes { get; set; }
        public virtual DbSet<quantityRange> quantityRanges { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
